In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## LOADING THE DATASET

In [3]:
dataset = pd.read_csv("covid_19_clean_complete.csv")
dataset

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...,...
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

## EXPLORING DATASET

In [4]:
dataset.head(50)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
5,NaN,Antigua and Barbuda,17.060800,-61.796400,2020-01-22,0,0,0,0,Americas
6,NaN,Argentina,-38.416100,-63.616700,2020-01-22,0,0,0,0,Americas
7,NaN,Armenia,40.069100,45.038200,2020-01-22,0,0,0,0,Europe
8,Australian Capital Territory,Australia,-35.473500,149.012400,2020-01-22,0,0,0,0,Western Pacific
9,New South Wales,Australia,-33.868800,151.209300,2020-01-22,0,0,0,0,Western Pacific
10,Northern Territory,Australia,-12.463400,130.845600,2020-01-22,0,0,0,0,Western Pacific
11,Queensland,Australia,-27.469800,153.025100,2020-01-22,0,0,0,0,Western Pacific
12,South Australia,Australia,-34.928500,138.600700,2020-01-22,0,0,0,0,Western Pacific
13,Tasmania,Australia,-42.882100,147.327200,2020-01-22,0,0,0,0,Western Pacific
14,Victoria,Australia,-37.813600,144.963100,2020-01-22,0,0,0,0,Western Pacific
15,Western Australia,Australia,-31.950500,115.860500,2020-01-22,0,0,0,0,Western Pacific
16,NaN,Austria,47.516200,14.550100,2020-01-22,0,0,0,0,Europe
17,NaN,Azerbaijan,40.143100,47.576900,2020-01-22,0,0,0,0,Europe
18,NaN,Bahamas,25.025885,-78.035889,2020-01-22,0,0,0,0,Americas
19,NaN,Bahrain,26.027500,50.550000,2020-01-22,0,0,0,0,Eastern Mediterranean
20,NaN,Bangladesh,23.685000,90.356300,2020-01-22,0,0,0,0,South-East Asia
21,NaN,Barbados,13.193900,-59.543200,2020-01-22,0,0,0,0,Americas
22,NaN,Belarus,53.709800,27.953400,2020-01-22,0,0,0,0,Europe
23,NaN,Belgium,50.833300,4.469936,2020-01-22,0,0,0,0,Europe
24,NaN,Benin,9.307700,2.315800,2020-01-22,0,0,0,0,Africa
25,NaN,Bhutan,27.514200,90.433600,2020-01-22,0,0,0,0,South-East Asia
26,NaN,Bolivia,-16.290200,-63.588700,2020-01-22,0,0,0,0,Americas
27,NaN,Bosnia and Herzegovina,43.915900,17.679100,2020-01-22,0,0,0,0,Europe
28,NaN,Brazil,-14.235000,-51.925300,2020-01-22,0,0,0,0,Americas
29,NaN,Brunei,4.535300,114.727700,2020-01-22,0,0,0,0,Western Pacific
30,NaN,Bulgaria,42.733900,25.485800,2020-01-22,0,0,0,0,Europe
31,NaN,Burkina Faso,12.238300,-1.561600,2020-01-22,0,0,0,0,Africa
32,NaN,Cabo Verde,16.538800,-23.041800,2020-01-22,0,0,0,0,Africa
33,NaN,Cambodia,11.550000,104.916700,2020-01-22,0,0,0,0,Western Pacific
34,NaN,Cameroon,3.848000,11.502100,2020-01-22,0,0,0,0,Africa
35,Alberta,Canada,53.933300,-116.576500,2020-01-22,0,0,0,0,Americas
36,British Columbia,Canada,53.726700,-127.647600,2020-01-22,0,0,0,0,Americas
37,Manitoba,Canada,53.760900,-98.813900,2020-01-22,0,0,0,0,Americas
38,New Brunswick,Canada,46.565300,-66.461900,2020-01-22,0,0,0,0,Americas
39,Newfoundland and Labrador,Canada,53.135500,-57.660400,2020-01-22,0,0,0,0,Americas
40,Nova Scotia,Canada,44.682000,-63.744300,2020-01-22,0,0,0,0,Americas
41,Ontario,Canada,51.253800,-85.323200,2020-01-22,0,0,0,0,Americas
42,Prince Edward Island,Canada,46.510700,-63.416800,2020-01-22,0,0,0,0,Americas
43,Quebec,Canada,52.939900,-73.549100,2020-01-22,0,0,0,0,Americas
44,Saskatchewan,Canada,52.939900,-106.450900,2020-01-22,0,0,0,0,Americas
45,NaN,Central African Republic,6.611100,20.939400,2020-01-22,0,0,0,0,Africa
46,NaN,Chad,15.454200,18.732200,2020-01-22,0,0,0,0,Africa
47,NaN,Chile,-35.675100,-71.543000,2020-01-22,0,0,0,0,Americas
48,Anhui,China,31.825700,117.226400,2020-01-22,1,0,0,1,Western Pacific
49,Beijing,China,40.182400,116.414200,2020-01-22,14,0,0,14,Western Pacific

In [5]:
dataset.tail(50)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
49018,NaN,Turkey,38.963700,35.243300,2020-07-27,227019,5630,210469,10920,Europe
49019,NaN,Uganda,1.373333,32.290275,2020-07-27,1128,2,986,140,Africa
49020,NaN,Ukraine,48.379400,31.165600,2020-07-27,67096,1636,37202,28258,Europe
49021,NaN,United Arab Emirates,23.424076,53.847818,2020-07-27,59177,345,52510,6322,Eastern Mediterranean
49022,Bermuda,United Kingdom,32.307800,-64.750500,2020-07-27,154,9,141,4,Europe
49023,Cayman Islands,United Kingdom,19.313300,-81.254600,2020-07-27,203,1,202,0,Europe
49024,Channel Islands,United Kingdom,49.372300,-2.364400,2020-07-27,584,47,533,4,Europe
49025,Gibraltar,United Kingdom,36.140800,-5.353600,2020-07-27,185,0,180,5,Europe
49026,Isle of Man,United Kingdom,54.236100,-4.548100,2020-07-27,336,24,312,0,Europe
49027,Montserrat,United Kingdom,16.742498,-62.187366,2020-07-27,12,1,10,1,Europe
49028,NaN,United Kingdom,55.378100,-3.436000,2020-07-27,300111,45759,0,254352,Europe
49029,NaN,Uruguay,-32.522800,-55.765800,2020-07-27,1202,35,951,216,Americas
49030,NaN,US,40.000000,-100.000000,2020-07-27,4290259,148011,1325804,2816444,Americas
49031,NaN,Uzbekistan,41.377491,64.585262,2020-07-27,21209,121,11674,9414,Europe
49032,NaN,Venezuela,6.423800,-66.589700,2020-07-27,15988,146,9959,5883,Americas
49033,NaN,Vietnam,14.058324,108.277199,2020-07-27,431,0,365,66,Western Pacific
49034,NaN,Zambia,-13.133897,27.849332,2020-07-27,4552,140,2815,1597,Africa
49035,NaN,Zimbabwe,-19.015438,29.154857,2020-07-27,2704,36,542,2126,Africa
49036,NaN,Dominica,15.415000,-61.371000,2020-07-27,18,0,18,0,Americas
49037,NaN,Grenada,12.116500,-61.679000,2020-07-27,23,0,23,0,Americas
49038,NaN,Mozambique,-18.665695,35.529562,2020-07-27,1701,11,0,1690,Africa
49039,NaN,Syria,34.802075,38.996815,2020-07-27,674,40,0,634,Eastern Mediterranean
49040,NaN,Timor-Leste,-8.874217,125.727539,2020-07-27,24,0,0,24,South-East Asia
49041,NaN,Belize,17.189900,-88.497600,2020-07-27,48,2,26,20,Americas
49042,NaN,Laos,19.856270,102.495496,2020-07-27,20,0,19,1,Western Pacific
49043,NaN,Libya,26.335100,17.228331,2020-07-27,2827,64,577,2186,Eastern Mediterranean
49044,NaN,West Bank and Gaza,31.952200,35.233200,2020-07-27,10621,78,3752,6791,Eastern Mediterranean
49045,NaN,Guinea-Bissau,11.803700,-15.180400,2020-07-27,1954,26,803,1125,Africa
49046,NaN,Mali,17.570692,-3.996166,2020-07-27,2513,124,1913,476,Africa
49047,NaN,Saint Kitts and Nevis,17.357822,-62.782998,2020-07-27,17,0,15,2,Americas
49048,Northwest Territories,Canada,64.825500,-124.845700,2020-07-27,5,0,0,5,Americas
49049,Yukon,Canada,64.282300,-135.000000,2020-07-27,14,0,0,14,Americas
49050,NaN,Kosovo,42.602636,20.902977,2020-07-27,7413,185,4027,3201,Europe
49051,NaN,Burma,21.916200,95.956000,2020-07-27,350,6,292,52,South-East Asia
49052,Anguilla,United Kingdom,18.220600,-63.068600,2020-07-27,3,0,3,0,Europe
49053,British Virgin Islands,United Kingdom,18.420700,-64.640000,2020-07-27,8,1,7,0,Europe
49054,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,2020-07-27,99,2,36,61,Europe
49055,NaN,Botswana,-22.328500,24.684900,2020-07-27,739,2,63,674,Africa
49056,NaN,Burundi,-3.373100,29.918900,2020-07-27,378,1,301,76,Africa
49057,NaN,Sierra Leone,8.460555,-11.779889,2020-07-27,1783,66,1317,400,Africa
49058,NaN,Malawi,-13.254300,34.301500,2020-07-27,3664,99,1645,1920,Africa
49059,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,2020-07-27,13,0,13,0,Europe
49060,Saint Pierre and Miquelon,France,46.885200,-56.315900,2020-07-27,4,0,1,3,Europe
49061,NaN,South Sudan,6.877000,31.307000,2020-07-27,2305,46,1175,1084,Africa
49062,NaN,Western Sahara,24.215500,-12.885800,2020-07-27,10,1,8,1,Africa
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

## INITIAL ANALYSIS

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [7]:
dataset.isnull().sum()

Province/State    34404
Country/Region        0
Lat                   0
Long                  0
Date                  0
Confirmed             0
Deaths                0
Recovered             0
Active                0
WHO Region            0
dtype: int64

## CHANGING THE COLUMN NAMES

In [9]:
col_names = ['_province_state', '_country_region', 'lat', 'long', 'date', 'confirmed', 'deaths', 'recovered', 'active', 'who_region']
dataset.columns = col_names
col_names

['_province_state',
 '_country_region',
 'lat',
 'long',
 'date',
 'confirmed',
 'deaths',
 'recovered',
 'active',
 'who_region']

In [10]:
dataset

,_province_state,_country_region,lat,long,date,confirmed,deaths,recovered,active,who_region
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...,...
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

In [11]:
dataset._province_state.unique()

array([nan, 'Australian Capital Territory', 'New South Wales',
       'Northern Territory', 'Queensland', 'South Australia', 'Tasmania',
       'Victoria', 'Western Australia', 'Alberta', 'British Columbia',
       'Manitoba', 'New Brunswick', 'Newfoundland and Labrador',
       'Nova Scotia', 'Ontario', 'Prince Edward Island', 'Quebec',
       'Saskatchewan', 'Anhui', 'Beijing', 'Chongqing', 'Fujian', 'Gansu',
       'Guangdong', 'Guangxi', 'Guizhou', 'Hainan', 'Hebei',
       'Heilongjiang', 'Henan', 'Hong Kong', 'Hubei', 'Hunan',
       'Inner Mongolia', 'Jiangsu', 'Jiangxi', 'Jilin', 'Liaoning',
       'Macau', 'Ningxia', 'Qinghai', 'Shaanxi', 'Shandong', 'Shanghai',
       'Shanxi', 'Sichuan', 'Tianjin', 'Tibet', 'Xinjiang', 'Yunnan',
       'Zhejiang', 'Faroe Islands', 'Greenland', 'French Guiana',
       'French Polynesia', 'Guadeloupe', 'Mayotte', 'New Caledonia',
       'Reunion', 'Saint Barthelemy', 'St Martin', 'Martinique', 'Aruba',
       'Curacao', 'Sint Maarten', 'Bermuda', 'Cayman Islands',
       'Channel Islands', 'Gibraltar', 'Isle of Man', 'Montserrat',
       'Northwest Territories', 'Yukon', 'Anguilla',
       'British Virgin Islands', 'Turks and Caicos Islands',
       'Falkland Islands (Malvinas)', 'Saint Pierre and Miquelon'],
      dtype=object)

In [12]:
most_province_state = dataset["_province_state"].value_counts()
most_province_state

_province_state
Australian Capital Territory    188
New South Wales                 188
Northern Territory              188
Queensland                      188
South Australia                 188
                               ...
Anguilla                        188
British Virgin Islands          188
Turks and Caicos Islands        188
Falkland Islands (Malvinas)     188
Saint Pierre and Miquelon       188
Name: count, Length: 78, dtype: int64

In [13]:
dataset.fillna({"_province_state":dataset["_province_state"].mode()[0]}, inplace=True)

In [14]:
dataset

,_province_state,_country_region,lat,long,date,confirmed,deaths,recovered,active,who_region
0,Alberta,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,Alberta,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,Alberta,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,Alberta,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,Alberta,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...,...
49063,Alberta,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,Alberta,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,Alberta,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,Alberta,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,Alberta,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa